//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("xmltv-lineups", Namespace="", IsNullable=false)]
public partial class xmltvLineupsType {
    
    private xmltvLineupType[] xmltvlineupField;
    
    private string modifiedField;
    
    private string sourceinfonameField;
    
    private string sourceinfourlField;
    
    private string sourcedataurlField;
    
    private string generatorinfonameField;
    
    private string generatorinfourlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("xmltv-lineup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public xmltvLineupType[] xmltvlineup {
        get {
            return this.xmltvlineupField;
        }
        set {
            this.xmltvlineupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modified {
        get {
            return this.modifiedField;
        }
        set {
            this.modifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-info-name")]
    public string sourceinfoname {
        get {
            return this.sourceinfonameField;
        }
        set {
            this.sourceinfonameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-info-url")]
    public string sourceinfourl {
        get {
            return this.sourceinfourlField;
        }
        set {
            this.sourceinfourlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-data-url")]
    public string sourcedataurl {
        get {
            return this.sourcedataurlField;
        }
        set {
            this.sourcedataurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("generator-info-name")]
    public string generatorinfoname {
        get {
            return this.generatorinfonameField;
        }
        set {
            this.generatorinfonameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("generator-info-url")]
    public string generatorinfourl {
        get {
            return this.generatorinfourlField;
        }
        set {
            this.generatorinfourlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class xmltvLineupType {
    
    private lineupTypeEnum typeField;
    
    private strWithLangAttrType[] displaynameField;
    
    private logoType[] logoField;
    
    private availabilityType[] availabilityField;
    
    private lineupEntryType[] lineupentryField;
    
    private string idField;
    
    private string modifiedField;
    
    private string sourceinfonameField;
    
    private string sourceinfourlField;
    
    private string sourcedataurlField;
    
    private string generatorinfonameField;
    
    private string generatorinfourlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public lineupTypeEnum type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("display-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public strWithLangAttrType[] displayname {
        get {
            return this.displaynameField;
        }
        set {
            this.displaynameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("logo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public logoType[] logo {
        get {
            return this.logoField;
        }
        set {
            this.logoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("availability", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public availabilityType[] availability {
        get {
            return this.availabilityField;
        }
        set {
            this.availabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lineup-entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public lineupEntryType[] lineupentry {
        get {
            return this.lineupentryField;
        }
        set {
            this.lineupentryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modified {
        get {
            return this.modifiedField;
        }
        set {
            this.modifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-info-name")]
    public string sourceinfoname {
        get {
            return this.sourceinfonameField;
        }
        set {
            this.sourceinfonameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-info-url")]
    public string sourceinfourl {
        get {
            return this.sourceinfourlField;
        }
        set {
            this.sourceinfourlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-data-url")]
    public string sourcedataurl {
        get {
            return this.sourcedataurlField;
        }
        set {
            this.sourcedataurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("generator-info-name")]
    public string generatorinfoname {
        get {
            return this.generatorinfonameField;
        }
        set {
            this.generatorinfonameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("generator-info-url")]
    public string generatorinfourl {
        get {
            return this.generatorinfourlField;
        }
        set {
            this.generatorinfourlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
public enum lineupTypeEnum {
    
    /// <remarks/>
    DTV,
    
    /// <remarks/>
    STB,
    
    /// <remarks/>
    IPTV,
    
    /// <remarks/>
    Analog,
    
    /// <remarks/>
    List,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class strWithLangAttrType {
    
    private string langField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class analogChanType {
    
    private string systemField;
    
    private string numberField;
    
    private string frequencyField;
    
    private string fcccallsignField;
    
    private analogChanTypeCni cniField;
    
    private string rfc2838Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string system {
        get {
            return this.systemField;
        }
        set {
            this.systemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fcc-callsign", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fcccallsign {
        get {
            return this.fcccallsignField;
        }
        set {
            this.fcccallsignField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public analogChanTypeCni cni {
        get {
            return this.cniField;
        }
        set {
            this.cniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfc2838 {
        get {
            return this.rfc2838Field;
        }
        set {
            this.rfc2838Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class analogChanTypeCni {
    
    private string tt8301Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("tt-8-30-1")]
    public string tt8301 {
        get {
            return this.tt8301Field;
        }
        set {
            this.tt8301Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class iptvChanType {
    
    private string iptvurlField;
    
    private string portField;
    
    private string rfc2838Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("iptv-url", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string iptvurl {
        get {
            return this.iptvurlField;
        }
        set {
            this.iptvurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfc2838 {
        get {
            return this.rfc2838Field;
        }
        set {
            this.rfc2838Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class stbChanType {
    
    private string stbpresetField;
    
    private string rfc2838Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stb-preset", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stbpreset {
        get {
            return this.stbpresetField;
        }
        set {
            this.stbpresetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfc2838 {
        get {
            return this.rfc2838Field;
        }
        set {
            this.rfc2838Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class dvbChanType {
    
    private string originalnetworkidField;
    
    private string transportidField;
    
    private string serviceidField;
    
    private string lcnField;
    
    private string servicenameField;
    
    private string providernameField;
    
    private bool encryptedField;
    
    private bool encryptedFieldSpecified;
    
    private string rfc2838Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("original-network-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string originalnetworkid {
        get {
            return this.originalnetworkidField;
        }
        set {
            this.originalnetworkidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transport-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string transportid {
        get {
            return this.transportidField;
        }
        set {
            this.transportidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string serviceid {
        get {
            return this.serviceidField;
        }
        set {
            this.serviceidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lcn {
        get {
            return this.lcnField;
        }
        set {
            this.lcnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string servicename {
        get {
            return this.servicenameField;
        }
        set {
            this.servicenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("provider-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string providername {
        get {
            return this.providernameField;
        }
        set {
            this.providernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool encrypted {
        get {
            return this.encryptedField;
        }
        set {
            this.encryptedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool encryptedSpecified {
        get {
            return this.encryptedFieldSpecified;
        }
        set {
            this.encryptedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfc2838 {
        get {
            return this.rfc2838Field;
        }
        set {
            this.rfc2838Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class audioType {
    
    private string formatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class videoType {
    
    private string formatField;
    
    private string aspectratioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("aspect-ratio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string aspectratio {
        get {
            return this.aspectratioField;
        }
        set {
            this.aspectratioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class stationType {
    
    private strWithLangAttrType nameField;
    
    private strWithLangAttrType shortnameField;
    
    private logoType[] logoField;
    
    private bool commercialfreeField;
    
    private bool commercialfreeFieldSpecified;
    
    private videoType videoField;
    
    private audioType audioField;
    
    private string rfc2838Field;
    
    private stationTypeEnum typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public strWithLangAttrType name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("short-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public strWithLangAttrType shortname {
        get {
            return this.shortnameField;
        }
        set {
            this.shortnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("logo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public logoType[] logo {
        get {
            return this.logoField;
        }
        set {
            this.logoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("commercial-free", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool commercialfree {
        get {
            return this.commercialfreeField;
        }
        set {
            this.commercialfreeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool commercialfreeSpecified {
        get {
            return this.commercialfreeFieldSpecified;
        }
        set {
            this.commercialfreeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public videoType video {
        get {
            return this.videoField;
        }
        set {
            this.videoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public audioType audio {
        get {
            return this.audioField;
        }
        set {
            this.audioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfc2838 {
        get {
            return this.rfc2838Field;
        }
        set {
            this.rfc2838Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public stationTypeEnum type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class logoType {
    
    private string urlField;
    
    private string heightField;
    
    private string widthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
public enum stationTypeEnum {
    
    /// <remarks/>
    TV,
    
    /// <remarks/>
    Radio,
    
    /// <remarks/>
    Data,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Text service")]
    Textservice,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class strWithTypeAttrType {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class lineupEntryType {
    
    private string presetField;
    
    private string sectionField;
    
    private strWithTypeAttrType[] packageField;
    
    private availabilityType[] availabilityField;
    
    private stationType stationField;
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string preset {
        get {
            return this.presetField;
        }
        set {
            this.presetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("package", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public strWithTypeAttrType[] package {
        get {
            return this.packageField;
        }
        set {
            this.packageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("availability", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public availabilityType[] availability {
        get {
            return this.availabilityField;
        }
        set {
            this.availabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public stationType station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("analog-channel", typeof(analogChanType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("dvb-channel", typeof(dvbChanType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("iptv-channel", typeof(iptvChanType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("stb-channel", typeof(stbChanType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class availabilityType {
    
    private availabilityAreaEnum areaField;
    
    private bool areaFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public availabilityAreaEnum area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
public enum availabilityAreaEnum {
    
    /// <remarks/>
    country,
    
    /// <remarks/>
    region,
    
    /// <remarks/>
    city,
    
    /// <remarks/>
    postcode,
    
    /// <remarks/>
    transmitter,
}
